# Generated by Django 3.2.8 on 2021-11-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('day_start', models.DateField()),
                ('dat_end', models.DateField()),
                ('type', models.CharField(max_length=128)),
                ('participant', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'challenge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='routineforce.challenge')),
                ('challenge_id', models.IntegerField()),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certification',
                'managed': False,
            },
        ),
    ]
