# Generated by Django 3.2.8 on 2021-11-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routineforce', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeRegistration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='routineforce.user')),
                ('status', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'challenge_registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=4096, null=True)),
                ('target', models.IntegerField()),
                ('date_and_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommonCode',
            fields=[
                ('value', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'common_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'heart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_in_point', models.IntegerField()),
                ('change_reason', models.CharField(max_length=10)),
                ('date_and_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'log_point',
                'managed': False,
            },
        ),
    ]
