# Generated by Django 3.2.8 on 2021-12-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routineforce', '0003_challengeregistration_comment_commoncode_heart_logpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('day_run', models.TextField()),
                ('dues', models.IntegerField(blank=True, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True)),
                ('headcount_min', models.IntegerField()),
                ('headcount_max', models.IntegerField()),
                ('location', models.CharField(max_length=128)),
                ('certification_type', models.CharField(max_length=10)),
                ('intro', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=4096)),
                ('body_type', models.CharField(max_length=10)),
                ('image_path', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'routine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_id', models.IntegerField()),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=4096, null=True)),
                ('result', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'routine_certification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineRegistration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='routineforce.user')),
                ('status', models.CharField(max_length=10)),
                ('result', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'routine_registration',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='challengeregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeRegistration',
        ),
    ]
