# Generated by Django 3.2.8 on 2021-12-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routineforce', '0004_auto_20211203_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('service', models.CharField(max_length=10)),
            ],
        ),
    ]
