# Generated by Django 3.2.8 on 2021-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routineforce', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_point', models.IntegerField()),
            ],
            options={
                'db_table': 'point',
                'managed': False,
            },
        ),
    ]
